### ISSUE TITLE
where is dump_qa.py

### ISSUE THREAD

**Issue by Charles1757** [adarsh-ops/semantic-qa#1]
hi, 
sorry to bother, but where is dump_qa.py?

**Comment by adarsh-ops** [comment]
Thanks for reporting the issue, I've added it, please check the latest commit

**Comment by Charles1757** [comment]
it works, thanks for your kindly sharing

**Comment by Charles1757** [comment]
> Thanks for reporting the issue. I've added it now, please check the latest commit
it works, thanks for your kindly sharing
